---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default] 
  - name: ubuntu-10.04
    run_list:
      - recipe[apt::default]
  - name: centos-7.0
  - name: centos-6.5
  - name: centos-5.10
    run_list:
      - recipe[yum-repoforge::default]

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
          datacenter: FortMeade
          bind_interface: eth0
          advertise_interface: eth0
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: source
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        install_method: source
  - name: runit
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
          datacenter: FortMeade
          init_style: runit
  - name: ui
    run_list:
      - recipe[consul::default]
      - recipe[consul::ui]
    attributes:
      consul:
         serve_ui: true
         client_interface: eth0
  - name: cluster
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service_mode: cluster
        bootstrap_expect: 1
