---
driver:
  name: dokken
  privileged: true
  env: [CHEF_LICENSE=accept]

transport:
  name: dokken

provisioner:
  name: dokken
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
    attributes:
      poise-service:
        consul:
          provider: systemd

  - name: centos-6
    driver:
      image: dokken/centos-6
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts net-tools
    attributes:
      poise-service:
        consul:
          provider: upstart

  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
    attributes:
      poise-service:
        consul:
          provider: upstart

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
    attributes:
      poise-service:
        consul:
          provider: systemd

  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release net-tools -y
    attributes:
      poise-service:
        consul:
          provider: systemd

  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
    attributes:
      poise-service:
        consul:
          provider: systemd

  - name: amazonlinux-2
    driver:
      image: dokken/amazonlinux-2
      pid_one_command: /usr/lib/systemd/systemd
    attributes:
      poise-service:
        consul:
          provider: systemd
