---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    named_run_list: centos
    driver:
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - /bin/yum install -y initscripts net-tools wget
suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/default.rb
    attributes:
      consul:
        config: &default-config
          owner: root
          group: consul
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
