---
language: ruby
cache: bundler
sudo: false
notifications:
  slack: bloomberg-rnd:BvYmxrV9xj902XWTRNrkLNkR
before_script:
  - bundle update
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
script: bundle exec rake travis
rvm:
  - 2.2
branches:
  only:
    - master
matrix:
  fast_finish: true
